import type { Metadata } from 'next';
import { headers } from 'next/headers';
import './globals.css';
import { Roboto } from 'next/font/google';

const roboto = Roboto({
  subsets: ['latin'],
  weight: ['300', '400', '600', '700'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const isProd = process.env.NODE_ENV === 'production';
  const headersList = await headers();
  const nonce = isProd ? headersList.get('x-nonce') || '' : '';
  return (
    <html lang='en'>
      <body nonce={nonce} className={`${roboto.className} antialiased`}>
        {children}
      </body>
    </html>
  );
}
