"""add credential_id and public_key to user

Revision ID: d47c788221af
Revises: c10f62facaa9
Create Date: 2025-05-25 17:11:10.677233

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd47c788221af'
down_revision: Union[str, None] = 'c10f62facaa9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('public_key', sa.String(), nullable=True))
    op.add_column('user', sa.Column('credential_id', sa.String(), nullable=True))
    op.create_index(op.f('ix_user_credential_id'), 'user', ['credential_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_credential_id'), table_name='user')
    op.drop_column('user', 'credential_id')
    op.drop_column('user', 'public_key')
    # ### end Alembic commands ###
