name: Build & Push Docker Image to GHCR

on:
  push:
    branches: [main]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read

    env:
      REGISTRY: ghcr.io
      IMAGE_NAME: ghcr.io/${{ github.repository }}:latest
      USERNAME: ${{ github.actor }}
      PASSWORD: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ env.USERNAME }}
          password: ${{ env.PASSWORD }}

      - name: Build Docker image
        run: |
          docker build -t $IMAGE_NAME -f backend/Dockerfile backend

      - name: Push Docker image to GHCR
        run: |
          docker push $IMAGE_NAME
